/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyBtn {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NativeTable {
    }
    interface NativeTableRender {
        "renderFun": Function;
    }
}
declare global {
    interface HTMLMyBtnElement extends Components.MyBtn, HTMLStencilElement {
    }
    var HTMLMyBtnElement: {
        prototype: HTMLMyBtnElement;
        new (): HTMLMyBtnElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNativeTableElement extends Components.NativeTable, HTMLStencilElement {
    }
    var HTMLNativeTableElement: {
        prototype: HTMLNativeTableElement;
        new (): HTMLNativeTableElement;
    };
    interface HTMLNativeTableRenderElement extends Components.NativeTableRender, HTMLStencilElement {
    }
    var HTMLNativeTableRenderElement: {
        prototype: HTMLNativeTableRenderElement;
        new (): HTMLNativeTableRenderElement;
    };
    interface HTMLElementTagNameMap {
        "my-btn": HTMLMyBtnElement;
        "my-component": HTMLMyComponentElement;
        "native-table": HTMLNativeTableElement;
        "native-table-render": HTMLNativeTableRenderElement;
    }
}
declare namespace LocalJSX {
    interface MyBtn {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NativeTable {
    }
    interface NativeTableRender {
        "renderFun"?: Function;
    }
    interface IntrinsicElements {
        "my-btn": MyBtn;
        "my-component": MyComponent;
        "native-table": NativeTable;
        "native-table-render": NativeTableRender;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-btn": LocalJSX.MyBtn & JSXBase.HTMLAttributes<HTMLMyBtnElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "native-table": LocalJSX.NativeTable & JSXBase.HTMLAttributes<HTMLNativeTableElement>;
            "native-table-render": LocalJSX.NativeTableRender & JSXBase.HTMLAttributes<HTMLNativeTableRenderElement>;
        }
    }
}
